# Site settings
title: Jaunt Journal
subtitle: of Ben & Beck's travels
email: jaunt@bmcintyre.co.uk
description: The meanderings of a couple struck with wanderlust
baseurl: ""
url: "http://jauntjournal.co.uk"
author: Ben McIntyre
street_address: Wandering
city: Free
state: 
zip_code: 
country: Nominally the UK
phone:
future: true

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
flickr_url: http://flickr.com/photos/bennbeck

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'http://jauntjournal.co.uk/'
  media: 'assets'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: True
      - name: "layout"
        field:
          label: "Layout"
          element: "select"
          value: "subpost"
          options: 
            - name: "post"
              value: "post"
            - name: "subpost"
              value: "subpost"
            - name: "post with map"
              value: "post-with-map"
      - name: "last_modified_at"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      planning: false

